vich_uploader:
    db_driver: orm
    mappings:
       annonces:
          uri_prefix: /img/Annonces
          upload_destination: '%kernel.project_dir%/public/img/Annonces'
          namer: Vich\UploaderBundle\Naming\UniqidNamer
          inject_on_load: false
          delete_on_update: true
          delete_on_remove: true

